In [ ]:
#Import Basic Packages

In [7]:
import numpy as np 
import pandas as pd
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [8]:
# Loading the iris dataest for building perceptron model
iris = datasets.load_iris()

In [12]:
# Create x and y data

x = iris.data
y = iris.target


#Apply the scaler to the training and test data

sc = StandardScaler()
x_std = sc.fit_transform(x)


In [13]:
x_std

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [14]:
# Splitting the data into train and test for building the model
x_train, x_test, y_train, y_test = train_test_split(x_std, y, test_size= 0.7, random_state= 101)

In [15]:
# Create model using Perceptron 
per_model = Perceptron(random_state = 101)
per_model.fit(x_train, y_train)

Perceptron(random_state=101)

In [16]:
#Predict the Model 

y_pred_train = per_model.predict(x_train)
y_pred_test = per_model.predict(x_test)

In [17]:
# accuracy_score, confusion_matrix, classification_report
print (classification_report(y_train, y_pred_train))
print ("######"*20)
print (classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92        12
           1       0.86      0.75      0.80        16
           2       0.84      0.94      0.89        17

    accuracy                           0.87        45
   macro avg       0.87      0.87      0.87        45
weighted avg       0.87      0.87      0.86        45

########################################################################################################################
              precision    recall  f1-score   support

           0       0.96      0.68      0.80        38
           1       0.60      0.82      0.69        34
           2       0.84      0.79      0.81        33

    accuracy                           0.76       105
   macro avg       0.80      0.77      0.77       105
weighted avg       0.81      0.76      0.77       105



In [18]:
# accuracy_score, confusion_matrix, classification_report
print (confusion_matrix(y_train, y_pred_train))
print ("######"*20)
print (confusion_matrix(y_test, y_pred_test))

[[11  1  0]
 [ 1 12  3]
 [ 0  1 16]]
########################################################################################################################
[[26 12  0]
 [ 1 28  5]
 [ 0  7 26]]


In [19]:
# accuracy_score, confusion_matrix, classification_report
print (accuracy_score(y_train, y_pred_train))
print ("######"*20)
print (accuracy_score(y_test, y_pred_test))

0.8666666666666667
########################################################################################################################
0.7619047619047619


In [21]:
# K-FOLD

from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(per_model, x_test,y_test, cv=10)
accuracy.mean()

0.7827272727272727